# fly.toml app configuration file generated for toradle-crypto on 2024-10-18T13:03:29+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'toradle-crypto'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
